# Generated by Django 5.1 on 2024-08-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_rename_eamil_booking_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingstatus',
            options={'verbose_name_plural': 'Booking Status'},
        ),
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('live_stream', 'Live Stream'), ('video_editing', 'Video Editing'), ('Event Planning', 'Event Planning')], default='live_stream', max_length=20),
        ),
    ]
