# Generated by Django 5.1 on 2024-08-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
