# Generated by Django 5.1 on 2024-08-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_bookingstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='eamil',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
