# Generated by Django 5.1 on 2024-08-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_program_schedules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program_Schedules',
            new_name='Program_Schedule',
        ),
    ]
