# Generated by Django 5.1 on 2024-08-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_rename_program_schedules_program_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program_Schedule',
        ),
    ]
